version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: udacity-postgres
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=fyyurdb
      - POSTGRES_USER=fyyur
      - POSTGRES_PASSWORD=fyyur
      - POSTGRES_PORT=5432